language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
before_install:
  - gem update bundler
env:
  - rvmsudo_secure_path=1
script: bundle exec rake test_all
services:
  - mongodb
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
bundler_args: --without test develop

branches: 
  only:
    - master
    - develop